# -*- coding: utf-8 -*-
"""Matthew_Abad_AOE_TokaMaker_Spring_2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sF-tDEX3dkZ2uUPs4SOK9hDN78yohy4Z

# Setup environment

###Load TokaMaker and helpful python packages
In this code segment, we import several helpful python packages and load in the TokaMaker code from GitHub. Default plotting values are also set here to make things more legible on most platforms. We also define a resize_polygon function which is helpful for defining geometries later on. **You do not need to change this code.**
"""

import os
import sys
import numpy as np
import matplotlib.pyplot as plt

plt.rcParams['figure.figsize']=(6,6)
plt.rcParams['font.weight']='bold'
plt.rcParams['axes.labelweight']='bold'
plt.rcParams['lines.linewidth']=2
plt.rcParams['lines.markeredgewidth']=2

# Commented out IPython magic to ensure Python compatibility.
try:
    from google.colab import output
    output.enable_custom_widget_manager()
except:
    tokamaker_python_path = os.getenv('OFT_ROOTPATH')
    if tokamaker_python_path is not None:
        sys.path.append(os.path.join(tokamaker_python_path,'python'))
#     %matplotlib inline
    pass
else:
    !pip install triangle wurlitzer ipympl
    OFT_package = 'OpenFUSIONToolkit_v1.0.0-beta6-Linux-GNU-x86_64'
    OFT_tarball = 'OpenFUSIONToolkit_v1.0.0-beta6-Ubuntu_22_04-GNU-x86_64.tar.gz'
    !wget https://github.com/openfusiontoolkit/OpenFUSIONToolkit/releases/download/v1.0.0-beta6/{OFT_tarball}
    !tar xzf {OFT_tarball}
    OFT_rootpath = os.path.join('/content',OFT_package)
    sys.path.append(os.path.join(OFT_rootpath,'python'))
#     %load_ext wurlitzer
#     %matplotlib inline

from OpenFUSIONToolkit.TokaMaker import TokaMaker
from OpenFUSIONToolkit.TokaMaker.meshing import gs_Domain, save_gs_mesh, load_gs_mesh
from OpenFUSIONToolkit.TokaMaker.util import create_isoflux, create_power_flux_fun
from OpenFUSIONToolkit import OFT_env

def resize_polygon(points, dx):
    new_points = np.empty(np.shape(points))
    for i in range(np.shape(points)[0]):
        if i==0:
            last = points[-1,:]
            next = points[i+1,:]
        elif i == np.shape(points)[0]-1:
            last = points[i-1,:]
            next = points[0,:]
        else:
            next = points[i+1,:]
            last = points[i-1,:]
        par = points[i,:]-last
        par/= np.linalg.norm(par)
        perp = np.array([par[1], -par[0]])
        temp = points[i,:] + perp*dx
        par_2 = next-points[i,:]
        par_2/= np.linalg.norm(par_2)
        perp_2 = [par_2[1], -par_2[0]]
        new_points[i, :] = temp + dx/np.dot(perp_2,par)*par  + par*dx/np.dot(par_2,perp)*np.dot(par_2,par)
    return new_points

"""# Setup device geometry
First, we need to tell TokaMaker what our tokamak should look like!

### Set mesh resolution
TokaMaker solves the Grad-Shafranov equation on a computational mesh. The finer the mesh is, the more accurate the solution will be. However, a finer mesh also decreases the speed of the solver. Here, we set a default resolution for the mesh in each domain. **You do not need to change these values.**
"""

#### DO NOT CHANGE ####
plasma_dx = 0.15
coil_dx = 0.15
vv_dx = 0.15
vac_dx = 0.25
#### DO NOT CHANGE ####

"""### Specify the geometry of the vacuum vessel

We need to decide on the shape of our vacuum vessel. We want to design a vacuum vessel that will fit our desired plasma shape. To visualize what our plasma looks like, we can use several quantities on your list of targets, including major radius, minor radius, elongation, and triangularity. Modify these quantities to correspond to your targets


"""

major_radius = 1.89
minor_radius = 0.57
elongation = 1.97
triangularity = 0.54

boundary_pts = create_isoflux(30,major_radius,0.0,minor_radius,elongation,triangularity)

"""Now, we have to decide the shape of our vacuum vessel cross-section. We do this by defining an array of (R,Z) coordinates for the vacuum vessel boundary. Every number in the array must be a float (a number including a decimal point). So, 3.5 and 3.0 are acceptable entries, but 3 is not."""

vv_boundary = np.array([[1.2, -1.2], [1.8,-1.2],[2.45, -0.7], [2.6, 0.0], [2.45,0.7],[1.8,1.2], [1.2,1.2]]) ##Add/change the vacuum vessel coordinates here!!!
vv_boundary = resize_polygon(boundary_pts, 0.02)

vv_outer = resize_polygon(vv_boundary, 0.04)

"""Now, you can plot the shape of the plasma and the vacuum vessel boundary to see what they look like.  If your plasma cross-section does not fit inside the vacuum vessel, go back and modify your vacuum vessel points!"""

fig, ax = plt.subplots()
ax.fill(vv_outer[:,0], vv_outer[:,1], color = 'k')
ax.fill(vv_boundary[:,0], vv_boundary[:,1], color = 'w')
ax.scatter(boundary_pts[:,0], boundary_pts[:,1], color = 'b')
ax.set_aspect(aspect = 1)
ax.set_xlabel('R (m)')
ax.set_ylabel('Z (m)')

"""### Place poloidal field coils
Now, we need to specify the locations of our poloidal field coils using (R,Z) coordinates. You can use a total of 8 poloidal field coils. You will need to change these coordinates to achieve the desired plasma shape.
"""

PF_1_R = 1.15
PF_1_Z = 1.60

PF_2_R = 1.15
PF_2_Z = -1.60

PF_3_R = 2.55
PF_3_Z = 1.60

PF_4_R = 2.55
PF_4_Z = -1.60

PF_5_R = 3.00
PF_5_Z = 1.00

PF_6_R = 3.00
PF_6_Z = -1.00

PF_7_R = 0.80
PF_7_Z = 0.70

PF_8_R = 0.80
PF_8_Z = -0.70

coil_locs = np.array([[PF_1_R, PF_1_Z], [PF_2_R, PF_2_Z], [PF_3_R, PF_3_Z], [PF_4_R, PF_4_Z], [PF_5_R, PF_5_Z], [PF_6_R, PF_6_Z], [PF_7_R, PF_7_Z], [PF_8_R, PF_8_Z]])

"""We can plot the locations of our coils and the vacuum vessel boundary. Make sure that the coils are outside of the vacuum vessel."""

fig, ax = plt.subplots()
ax.fill(vv_outer[:,0], vv_outer[:,1], color = 'k')
ax.fill(vv_boundary[:,0], vv_boundary[:,1], color = 'w')
ax.scatter(boundary_pts[:,0], boundary_pts[:,1], color = 'b')
ax.scatter(coil_locs[:,0], coil_locs[:,1], color = 'r')
ax.set_aspect(aspect = 1)
ax.set_xlabel('R (m)')
ax.set_ylabel('Z (m)')

"""### Define the regions of our tokamak
We have to tell the solver what domains we plan on implementing in our tokamak. For this device, we implement four types of domains:
1.   An air domain, which surrounds the tokamak
2.   A vaccum vessel domain, for the vacuum vessel containing the plasma
3.   A plasma domain, where the plasma will be located
4.   Eight poloidal field coil domains, which contain the coils we will use to shape the plasma

**You do not need to change this code.**


"""

#### DO NOT CHANGE ####
# Create a mesh object
mesh = gs_Domain()
# Define region information for mesh
mesh.define_region('air',vac_dx,'boundary')        # Air domain
mesh.define_region('vv',vv_dx,'conductor',eta= 6.9E-7)      # Vaccum vessel domain
mesh.define_region('plasma',plasma_dx,'plasma')    # Plasma domain
# Define each of the PF coils
for i in range(1,9):
    mesh.define_region('PF_' + str(i),coil_dx,'coil') # Coil domains
#### DO NOT CHANGE ####

"""## Add region boundaries to our gs_Domain object
Now that we have decided on our geometry, we need to pass that information on to the mesh object. **You do not need to modify this code.**
"""

#### DO NOT CHANGE ####
# Define geometry
mesh.add_annulus(vv_boundary,'plasma',vv_outer,'vv',parent_name='air') # Define the shape of the VV

# Define the shape of the PF coils
for i in range(1,9):
    mesh.add_rectangle(coil_locs[i-1,0],coil_locs[i-1,1],0.3,0.3,'PF_' + str(i),parent_name='air')
#### DO NOT CHANGE ####

fig, ax = plt.subplots(1,1,figsize=(4,6),constrained_layout=True)
mesh.plot_topology(fig,ax)

"""### Generate mesh
Now we generate the actual mesh that TokaMaker will use to solve the Grad Shafranov equation. We also plot the mesh to make sure that each region is defined properly. **You do not need to change this code.**
"""

#### DO NOT CHANGE ####
mesh_pts, mesh_lc, mesh_reg = mesh.build_mesh()
coil_dict = mesh.get_coils()
cond_dict = mesh.get_conductors()
#### DO NOT CHANGE ####

# fig, ax = plt.subplots(1,1,figsize=(5,5),constrained_layout=True)
# mesh.plot_mesh(fig,ax)

"""# Find a plasma equilibrium

### Setup TokaMaker
Now that we have set up our device, we are ready to solve for an equilibrium. First, we need to make a new object of the TokaMaker class. Make sure to only run this cell one time per Google Colab notebook, or you may get an error.


"""

#### DO NOT CHANGE ####
myOFT = OFT_env(nthreads=1)
tokamaker = TokaMaker(myOFT)
#### DO NOT CHANGE ####

"""### Load Mesh Information
Now, we load the mesh we just generated into the TokaMaker object. If you go back and modify the mesh and would like to update it in the tokamaker model, uncomment the

```
tokamaker.reset()
```
line, which will allow you to setup a new mesh.

"""

tokamaker.reset()
tokamaker.setup_mesh(mesh_pts, mesh_lc, mesh_reg)
tokamaker.setup_regions(cond_dict=cond_dict,coil_dict=coil_dict)

"""### Set magnetic field and major radius

Here, we specify the magnetic field and major radius of the plasma. You should change these values to match your target parameters.
"""

B0 = 12.2 #toroidal magnetic field
R0 = 1.85 #major radius

tokamaker.setup(order=2,F0=B0*R0)

"""### Define global quantities and targets

We need to tell the solver a bit more information about our device. First, we need to specify the total current in the plasma, by setting a target value for 'Ip'.

We also need to specify a target for the plasma pressure in the core of the tokamak. To do this, we set a number for the 'p_core_target'.

You will likely need to adjust these quantities to match other design targets, such as an appropriate q-profile and the correct poloidal beta ($\beta_p$).
"""

Ip_target = 6.8E6
p_core_target = 3.4E6

tokamaker.set_targets(Ip=Ip_target,pax = p_core_target)

"""### Define plasma profiles

The magnitudes of the F*F' and P' profiles are determined by the global quantities set above.  Now, we need to specify the actual shape of the profiles. For simplicity, we will use simple polynomial profiles of the form
 $((1-\hat{\psi})^{\alpha})^{\gamma}$ using the built-in TokaMaker function 'create_power_flux_fun'.

 Feel free to adjust the alpha ($\alpha$) and gamma ($\gamma$) parameters for both P' and F*F' to reach your desired internal inductance ($l_i$) target.

"""

ffp_alpha = 1.8
ffp_gamma = 1.0

pp_alpha = 0.5
pp_gamma = 0.5

ffp_prof = create_power_flux_fun(40,ffp_alpha,ffp_gamma)
pp_prof = create_power_flux_fun(40,pp_alpha,pp_gamma)

tokamaker.set_profiles(ffp_prof=ffp_prof,pp_prof=pp_prof)

"""Now, we can visualize our profiles. "Peaked" profiles, which are more concentrated around $\Psi$ = 0, correspond to higher internal inductance ($l_i$)."""

# fig, ax = plt.subplots(2,1,sharex=True)
# # Plot F*F'
# ax[0].plot(ffp_prof['x'],ffp_prof['y'])
# ax[0].set_ylabel("FF'")
# # Plot P'
# ax[1].plot(pp_prof['x'],pp_prof['y'])
# ax[1].set_ylabel("P'")
# _ = ax[-1].set_xlabel(r"$\hat{\psi}$")

"""### Set shape targets

Now we need to tell TokaMaker what the shape of our plasma cross-section will look like. Given that we've already made an array of points defining our plasma, we just need to pass this array to the set_isoflux() method. **You do not need to change this code**.
"""

tokamaker.set_isoflux(boundary_pts, weights = 5*np.ones(len(boundary_pts)))

"""### Set up coil regularization

This code segment makes sure that the solver tries to minimize the currents in each coil. **You should not change this code**
"""

#### DO NOT CHANGE ####
regularization_terms = []
for name in coil_dict.keys():
  # Set zero target current and small weight to help conditioning of fit
  regularization_terms.append(tokamaker.coil_reg_term({name: 1.0},target=0.0,weight=1.E-1))

# Pass regularization terms to TokaMaker
tokamaker.set_coil_reg(reg_terms=regularization_terms)
#### DO NOT CHANGE ####

"""Now we are ready to solve. **You shouldn't have to edit any of this code.**"""

#### DO NOT CHANGE ####
tokamaker.init_psi(major_radius,0.0,minor_radius,elongation,triangularity)
err_flag = tokamaker.solve()
#### DO NOT CHANGE ####

"""### Check for convergence
This code prints out err_flag. If it is anything other than 'None', the solver has failed.
"""

print(err_flag)

"""# Analyze equilibrium

Now we are ready to analyze our equilibrium and check how it performs against our desired metrics.

### Plot equilibrium solution

The red crosses correspond to our target plasma boundary. Check if this lines up with the actual plasma boundary. If they are not similar, you may need to adjust your coil positions to create your desired shape.

**You do not need to change this code.**

"""

#### DO NOT CHANGE ####
fig, ax = plt.subplots()
tokamaker.plot_machine(fig,ax)
tokamaker.plot_psi(fig,ax)
tokamaker.plot_constraints(fig,ax)
#### DO NOT CHANGE ####

"""### Print equilibrium statistics

TokaMaker has a built-in function to compute a bunch of relevant quantities for an equilibrium. There are a few things you should take note of:

1.   Where is the current centroid? Is it close to your desired major radius? If not, you may need to adjust your coil positions to better match the target shape. (Cell 9)
2.   What is the elongation? Is it close to your target elongation? If not, you may need to adjust your coil positions to better match the target shape. (Cell 9)
3.   What is the triangularity. Is it close to the target triangularity? If not, you may need to adjust your coil positions to better match the target shape. (Cell 9)
4.   What is your q_95? Is it less than 2.5? If so, you may need to decrease your target plasma current (Ip) to increase this number.  Is it way above 4? If so, you may want to increase your plasma current to decrease this number. (Cell 20)
5. What is your beta_pol? Is it close to your target beta_pol? If not, you might need to adjust your p_core_target. (Cell 20)
6. What is your internal inductance(l_i) ? Is it close to your target l_i? If not, you may need to alter the alpha and gamma factors in your FF' and P' profile shapes to alter this number. (Cell 21)


"""

tokamaker.print_info()

"""We can also save all of this equilibrium information in a python dictionary, so we can access it later if needed."""

eq_info = tokamaker.get_stats()

"""### Plot coil currents

For our device to be efficient, we want the currents in our poloidal field coils to be low. Here, we check if our poloidal field coil currents are more than two times the plasma current by plotting our coil currents and the current limit (dashed red line).

If any coil has current greater than two times the plasma current, try to adjust your coil positions to reduce their currents. Some things to try:


*   Move your coils closer to the plasma (this may require modifying your vacuum vessel)
*   Move your coils apart from one another, so they don't have to compete


"""

# fig,ax = plt.subplots(figsize = (8,6))

# coil_currents, ___ = tokamaker.get_coil_currents()

# for key in coil_dict.keys():
#   ax.scatter(key, np.abs(coil_currents[key]/1E6), color = 'tab:blue')

# coil_current_limit = eq_info['Ip']*2
# ax.hlines(coil_current_limit/1E6, xmin = 0, xmax = len(coil_dict.keys()), color = 'r', linestyle = '--')

# ax.set_xlabel('Coil name')
# ax.set_ylabel('Coil current (MA)')
# fig.close()

"""### Check vertical stability

Plasmas in tokamaks with elongation greater than 1 can be susceptible to a "vertical instability", where the plasma moves up or down within the vacuum vessel at an exponential rate. Here, we check whether the growth rate of our vertical instability is low enough that it can be prevented with a control system.

If the "feedback capability parameter" is greater than 2, modify your vacuum vessel to make it closer to the plasma, because the vaccum vessel can help provide vertical stability.

**You do not need to change this code.**
"""

#### DO NOT CHANGE ####
eig_vals, eig_vecs = tokamaker.eig_td(omega = -1E4, neigs = 10)
growth_rate = -eig_vals[0,0]

eigval_wall, eigvec_wall = tokamaker.eig_wall()
wall_time = 1/eigval_wall[1,0]

feedback_capability_param = growth_rate*wall_time
print('Feedback capability parameter: ' + str(feedback_capability_param))
print('Growth rate: ' + str(growth_rate))
#### DO NOT CHANGE ####

tokamaker.settings.pm=False
tokamaker.update_settings()
mygs = tokamaker

"""Compute linear stability as a function of $\beta_p$"""

growth = []
beta_p = []
modes = []
zhist = []
equil_histories = []
vde_fail_reason = []

# Reinitialize from a valid baseline equilibrium before scanning.
mygs.set_isoflux(boundary_pts)
mygs.set_targets(Ip=Ip_target, pax=p_core_target)
mygs.init_psi(major_radius, 0.0, minor_radius, elongation, triangularity)
try:
    mygs.solve()
except ValueError as exc:
    raise RuntimeError('Failed to reinitialize baseline equilibrium before beta scan.') from exc

# Build a device-specific scan around the currently converged equilibrium.
try:
    beta_ref = max(1.0e-6, mygs.get_stats()['beta_pol'])
except Exception:
    if ('eq_info' in globals()) and isinstance(eq_info, dict) and np.isfinite(eq_info.get('beta_pol', np.nan)):
        beta_ref = max(1.0e-6, float(eq_info['beta_pol']))
        print('Using beta_pol from eq_info as baseline.')
    else:
        raise RuntimeError('Unable to determine baseline beta_pol for scan.')

beta_targets = beta_ref * np.linspace(0.8, 1., 5)
# beta_targets = np.linspace(0.6, 1.0, 10) * 100

for beta_target in beta_targets:
    print('Computing target beta_p [%] {0:.3f}'.format(beta_target))
    mygs.set_isoflux(boundary_pts)
    mygs.init_psi(major_radius, 0.0, minor_radius, elongation, triangularity)

    # Pressure scan is more robust than directly reusing CUTE Ip_ratio tuning.
    p_target = p_core_target * (beta_target / beta_ref)
    err_flag = None
    for _ in range(6):
        mygs.set_targets(Ip=Ip_target, pax=p_target)
        try:
            mygs.solve()
        except ValueError as exc:
            err_flag = exc
            break

        beta_now = mygs.get_stats()['beta_pol']
        if (not np.isfinite(beta_now)) or (beta_now <= 0.0):
            err_flag = ValueError('invalid beta_pol from equilibrium')
            break

        scale = np.clip(beta_target / beta_now, 0.7, 1.4)
        p_target *= scale
        if abs(beta_now - beta_target) / beta_target < 0.03:
            break

    if err_flag is not None:
        print('  Equilibrium failed for this target; recording NaN and continuing.')
        beta_p.append(np.nan)
        growth.append(np.nan)
        modes.append(np.zeros_like(mygs.get_psi(False)))
        zhist.append([[0.0, mygs.o_point[1]]])
        equil_histories.append([])
        vde_fail_reason.append('equilibrium_solve_failed')
        continue

    beta_now = mygs.get_stats()['beta_pol']
    beta_p.append(beta_now)
    print('  Actual beta_p = {0:.3f}'.format(beta_now))

    psi0 = mygs.get_psi(False)

    # Compute linear stability.
    eig_vals, eig_vecs = mygs.eig_td(-1.0e5, 10, False)
    upper_mask = mygs.r[:, 1] > 0.0
    eig_sign = eig_vecs[0, upper_mask][np.abs(eig_vecs[0, upper_mask]).argmax()]
    if abs(eig_sign) < 1.0e-12:
        eig_sign = 1.0
    mode0 = eig_vecs[0, :] / eig_sign
    modes.append(mode0)
    growth.append(eig_vals[0, 0])

    # Compute nonlinear evolution for a longer physical window.
    psi_ic = psi0 - 0.01 * mode0 * (mygs.psi_bounds[1] - mygs.psi_bounds[0])
    mygs.set_psi(psi_ic)
    mygs.set_isoflux(None)

    growth_mag = max(abs(eig_vals[0, 0]), 1.0)
    target_efolds = 6.0
    sim_end_time = float(np.clip(target_efolds / growth_mag, 8.0e-2, 4.0e-1))
    target_samples = 450
    dt = min(0.2 / growth_mag, 5.0e-4, sim_end_time / target_samples)
    dt = max(dt, 1.0e-6)

    mygs.setup_td(dt, 1.0e-13, 1.0e-11)

    sim_time = 0.0
    z0 = [[sim_time, mygs.o_point[1]]]
    equil_case = []
    if hasattr(mygs, '_tMaker_equil') and (mygs._tMaker_equil is not None):
        equil_case.append(mygs._tMaker_equil.copy())

    step_count = 0
    max_steps = 2000
    failure_reason = 'completed'
    dz_peak = 0.0
    while (sim_time < sim_end_time) and (step_count < max_steps):
        sim_time_next, _, nl_its, lin_its, nretry = mygs.step_td(sim_time, dt)
        if nretry < 0:
            dt *= 0.5
            if dt < 1.0e-8:
                print('  Nonlinear evolution stopped: dt became too small.')
                failure_reason = 'td_no_convergence'
                break
            mygs.setup_td(dt, 1.0e-13, 1.0e-11)
            continue

        if nretry >= 5:
            print('  Nonlinear evolution stopped: excessive retries in step solve.')
            failure_reason = 'excessive_retries'
            break

        sim_time = sim_time_next
        step_count += 1

        psi_now = mygs.get_psi(False)
        if not np.all(np.isfinite(psi_now)):
            print('  Nonlinear evolution stopped: non-finite psi encountered.')
            failure_reason = 'non_finite_psi'
            break

        dz_step = abs(mygs.o_point[1] - z0[0][1])
        dz_peak = max(dz_peak, dz_step)
        if (step_count > 20) and (dz_peak > 5.0e-3) and (dz_step < 0.25 * dz_peak):
            print('  Nonlinear evolution stopped: lost axis tracking after Delta Z collapse.')
            failure_reason = 'axis_tracking_lost'
            break

        z0.append([sim_time, mygs.o_point[1]])
        if hasattr(mygs, '_tMaker_equil') and (mygs._tMaker_equil is not None):
            equil_case.append(mygs._tMaker_equil.copy())

    if step_count >= max_steps:
        print('  Nonlinear evolution stopped: reached max step count.')
        failure_reason = 'max_steps'

    if step_count == 0 and failure_reason == 'completed':
        failure_reason = 'no_progress'

    print('  Nonlinear evolution time reached: {0:.1f} ms ({1:d} steps)'.format(sim_time * 1.0e3, step_count))

    zhist.append(z0)
    equil_histories.append(equil_case)
    vde_fail_reason.append(failure_reason)

beta_arr = np.asarray(beta_p, dtype=float)
growth_arr = np.asarray(growth, dtype=float)
valid = np.isfinite(beta_arr) & np.isfinite(growth_arr)

fig, ax = plt.subplots(1, 1)
if np.any(valid):
    ax.plot(beta_arr[valid], growth_arr[valid], marker='o')
else:
    print('No valid beta scan points were found.')
ax.set_ylim(top=0.0)
ax.grid(True)
ax.set_ylabel(r'$\gamma$ [1/s]')
_ = ax.set_xlabel(r'$\beta_p$ [%]')

# ax.set_xlim(50,100)

"""### Plot linear eigenmodes

"""

# beta_arr = np.asarray(beta_p, dtype=float)
# growth_arr = np.asarray(growth, dtype=float)
# valid_idx = np.where(np.isfinite(beta_arr) & np.isfinite(growth_arr))[0]
# if len(valid_idx) < 4:
#     raise RuntimeError('Need at least 4 successful beta points to plot eigenmodes.')
# plot_idx = valid_idx[np.linspace(0, len(valid_idx) - 1, 4, dtype=int)]

# scalarMap = plt.cm.ScalarMappable(cmap=plt.cm.viridis)
# scalarMap.set_clim(vmin=beta_arr[valid_idx].min(), vmax=beta_arr[valid_idx].max())

# fig, ax = plt.subplots(1, 4, sharey=True, constrained_layout=True, figsize=(8, 4))
# for ax_tmp in ax:
#     mygs.plot_machine(fig, ax_tmp, limiter_color=None)

# for j, i in enumerate(plot_idx):
#     colorVal = scalarMap.to_rgba(beta_arr[i])
#     mygs.plot_psi(
#         fig,
#         ax[j],
#         psi=modes[i],
#         plasma_nlevels=6,
#         normalized=False,
#         plasma_color=[colorVal],
#         opoint_color=None,
#         xpoint_color=None,
#         vacuum_nlevels=0
#     )
#     mygs.plot_eddy(
#         fig,
#         ax[j],
#         dpsi_dt=modes[i] * abs(growth_arr[i]),
#         colormap='seismic',
#         symmap=True,
#         clabel=None
#     )

# for ax_tmp in ax:
#     ax_tmp.set_xlabel(r'R [m]')
# ax[0].set_ylabel(r'Z [m]')
# _ = fig.colorbar(scalarMap, ax=ax[:], label=r'$\beta_p$ [%]')

# fig.close()

"""Plot nonlinear plasma evolution"""

# beta_arr = np.asarray(beta_p, dtype=float)

# fig, ax = plt.subplots(1, 1)
# for i, z0 in enumerate(zhist):
#     if (i >= len(beta_arr)) or (not np.isfinite(beta_arr[i])) or (len(z0) < 4):
#         continue

#     z_arr = np.asarray(z0, dtype=float)
#     t_ms = z_arr[:, 0] * 1.0e3
#     dz_abs = np.abs(z_arr[:, 1] - z_arr[0, 1])

#     # Drop the baseline point (Delta Z0 = 0) to avoid a nonphysical vertical jump on log scale.
#     t_ms = t_ms[1:]
#     dz_abs = dz_abs[1:]

#     finite_mask = np.isfinite(t_ms) & np.isfinite(dz_abs)
#     t_ms = t_ms[finite_mask]
#     dz_abs = dz_abs[finite_mask]
#     if len(t_ms) < 3:
#         continue

#     # Remove duplicate/non-increasing times that can arise from failed retries.
#     keep = np.ones(len(t_ms), dtype=bool)
#     keep[1:] = np.diff(t_ms) > 0.0
#     t_ms = t_ms[keep]
#     dz_abs = dz_abs[keep]
#     if len(t_ms) < 3:
#         continue

#     # Trim nonphysical collapse tail when the axis location tracker has failed.
#     peak = np.maximum.accumulate(dz_abs)
#     collapse_mask = (peak > 5.0e-3) & (dz_abs < 0.25 * peak)
#     if np.any(collapse_mask):
#         cut_idx = np.where(collapse_mask)[0][0]
#         t_ms = t_ms[:cut_idx]
#         dz_abs = dz_abs[:cut_idx]
#     if len(t_ms) < 3:
#         continue

#     # Densify on a uniform time axis and smooth in log space to reduce staircase artifacts.
#     n_interp = max(220, min(900, len(t_ms) * 3))
#     t_plot = np.linspace(t_ms[0], t_ms[-1], n_interp)
#     log_dz = np.log10(np.maximum(dz_abs, 1.0e-10))
#     log_plot = np.interp(t_plot, t_ms, log_dz)

#     if len(log_plot) >= 9:
#         win = 9
#         kernel = np.ones(win) / win
#         log_smooth = np.convolve(log_plot, kernel, mode='same')
#         half = win // 2
#         log_smooth[:half] = log_plot[:half]
#         log_smooth[-half:] = log_plot[-half:]
#         log_plot = log_smooth

#     dz_plot = 10.0 ** log_plot

#     colorVal = scalarMap.to_rgba(beta_arr[i])
#     ax.semilogy(t_plot, dz_plot, color=colorVal)

#     fail_reason = 'completed'
#     if ('vde_fail_reason' in globals()) and (i < len(vde_fail_reason)):
#         fail_reason = vde_fail_reason[i]
#     if fail_reason != 'completed':
#         ax.scatter(t_plot[-1], dz_plot[-1], color=colorVal, marker='x', s=36)

# ax.grid(True)
# ax.set_ylabel(r'$|\Delta Z_0|$ [m]')
# ax.set_xlabel(r'Time [ms]')
# _ = fig.colorbar(scalarMap, ax=ax, label=r'$\beta_p$ [%]')

# fig.close()

"""### Plot VDE equilibrium snapshots over time
Using the nonlinear time traces, this reproduces the CUTE-style end plots that show how each scanned equilibrium evolves during the VDE.
"""

beta_arr = np.asarray(beta_p, dtype=float)

if 'equil_histories' not in globals():
    raise RuntimeError('Run the beta scan cell first so equil_histories is available.')

n_snapshots = 8
for i, (z0, equil_case) in enumerate(zip(zhist, equil_histories)):
    if (i >= len(beta_arr)) or (not np.isfinite(beta_arr[i])) or (not equil_case):
        continue

    snap_ids = np.unique(np.linspace(0, len(equil_case) - 1, n_snapshots, dtype=int))
    z_arr = np.asarray(z0)

    if len(z_arr) != len(equil_case):
        print(f'Warning: zhist/equil length mismatch for case {i}: {len(z_arr)} vs {len(equil_case)}')

    fig, ax = plt.subplots(
        1,
        len(snap_ids),
        figsize=(3.6 * len(snap_ids), 4.0),
        sharey=True,
        constrained_layout=True
    )
    if len(snap_ids) == 1:
        ax = [ax]

    invalid_reached = False
    for j, snap in enumerate(snap_ids):
        if invalid_reached:
            ax[j].axis('off')
            continue

        z_idx = min(snap, len(z_arr) - 1)
        mygs.plot_machine(fig, ax[j], limiter_color=None)

        t_ms = z_arr[z_idx, 0] * 1.0e3
        dz_mm = (z_arr[z_idx, 1] - z_arr[0, 1]) * 1.0e3

        try:
            mygs.plot_psi(
                fig,
                ax[j],
                equilibrium=equil_case[snap],
                xpoint_color='k',
                vacuum_nlevels=6,
                plasma_nlevels=6
            )
            ax[j].set_title(f't = {t_ms:.2f} ms\nDelta Z0 = {dz_mm:+.2f} mm')
        except Exception:
            ax[j].text(
                0.5,
                0.5,
                'Equilibrium no longer finite',
                transform=ax[j].transAxes,
                ha='center',
                va='center'
            )
            ax[j].set_title(f't = {t_ms:.2f} ms\nInvalid equilibrium state')
            invalid_reached = True

        ax[j].set_xlabel(r'R [m]')

    ax[0].set_ylabel(r'Z [m]')
    fig.suptitle('VDE equilibrium evolution (beta_p = {:.2f}%)'.format(beta_arr[i]))